/*User Reducer Types */
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const SET_SUBSCRIPTION = "SET_SUBSCRIPTION";

/* UI REDUCER TYPES */
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
export const SET_DASHBOARD = "SET_DASHBOARD";

/* DATA REDUCER TYPES */
export const SET_SELECTED_USER = "SET_SELECTED_USER";
export const SET_USERS = "SET_USERS";
export const LOADING_DATA = "LOADING_DATA";
export const SET_BOOK = "SET_BOOK";
export const SET_BOOKS = "SET_BOOKS";
export const SET_MOVIE = "SET_MOVIE";
export const SET_MOVIES = "SET_MOVIES";
export const SET_DATES = "SET_DATES";
export const SET_RESERVATION = "SET_RESERVATION";
export const SET_RESERVATIONS = "SET_RESERVATIONS";
export const SET_BOOK_PRICES = "SET_BOOK_PRICES";
export const SET_MOVIE_PRICES = "SET_MOVIE_PRICES";
export const SET_COMPANY_PURCHASES_BOOKS = "SET_COMPANY_PURCHASES_BOOKS";
export const SET_COMPANY_PURCHASES_MOVIES = "SET_COMPANY_PURCHASES_MOVIES";
export const SET_UPDATE_CSV = "SET_UPDATE_CSV";
export const SET_API_RESULT = "SET_API_RESULT";
export const SET_BOOK_FAVORITES = "SET_BOOK_FAVORITES";
export const SET_BOOKS_SECONDARY_DB = "SET_BOOKS_SECONDARY_DB";

//  CART REDUCER TYPES
export const ADD_TO_LIST = "ADD_TO_LIST";
export const REMOVE_FROM_LIST = "REMOVE_FROM_LIST";
export const GET_TOTAL_BOOKS = "GET_TOTAL_BOOKS";
export const CLEAR_CART = "CLEAR_CART";
export const ADD_TO_MOVIE_LIST = "ADD_TO_MOVIE_LIST";
export const REMOVE_FROM_MOVIE_LIST = "REMOVE_FROM_MOVIE_LIST";
export const CLEAR_MOVIE_CART = "CLEAR_MOVIE_CART";
